name: poc-cgsnap
base: core24
version: '0.1'
summary: Testing possibility of manage cgroups using a strictly confined snap
description: |
  PoC testing the possibility of manage cgroups filesystem from a strictly
  confiined snap

grade: stable
confinement: strict

parts:
  src:
    plugin: dump
    source: .
    source-type: local

apps:
  run:
    command: run
