name: poc-cgsnap
base: core24
version: '0.1'
summary: Testing possibility of manage cgroups using a strictly confined snap
description: |
  PoC testing the possibility of manage cgroups filesystem from a strictly
  confiined snap

grade: stable
confinement: strict

plugs:
  sys-fs-cgroup:
    interface: system-files
    write:
      - /sys/fs/cgroup

parts:
  src:
    plugin: dump
    source: .
    source-type: local

apps:
  run:
    command: run
    plugs:
      - sys-fs-cgroup
      - log-observe
